name: starter_app
description: Flutter starter app

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  connectivity_plus: ^5.0.2
  dio: ^5.2.1+1
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  google_fonts: ^6.1.0
  grouped_list: ^5.1.2
  hexcolor: ^3.0.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  like_button: ^2.0.5
  package_info_plus: ^5.0.1
  pinput: ^4.0.0
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  stacked: ^3.4.1
  stacked_services: ^1.2.0
  syncfusion_flutter_charts: ^24.2.6

dev_dependencies:
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  freezed: ^2.3.5
  stacked_generator: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
